Downgrade eslint to fix travis build
Trying to fix this:

> leaflet-clonelayer@1.0.3 lint /home/travis/build/jieter/leaflet-clonelayer
> eslint index.js test/spec.js test/index.html
/home/travis/build/jieter/leaflet-clonelayer/node_modules/eslint/bin/eslint.js:39
process.once("uncaughtException", err => {
                                  ^^^
SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:471:10)
    at startup (node.js:117:18)
    at node.js:951:3